name: tag

on:
  push:
    tags:
      - '*'

jobs:
  goproxy:
    runs-on: ubuntu-latest
    container:
      image: golang:1.15.3-alpine3.12
    steps:
      - name: Resolve
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: on
        run: go get github.com/alonsopf/golang-unsplash
